// user
export const INIT_USER_INFO = 'INIT_USER_INFO'
export const INIT_PMTD_ROUTES = 'INIT_PMTD_ROUTES'

// loglist
export const SET_LOGLIST_SIDEBAR_INDEX = 'SET_LOGLIST_SIDEBAR_INDEX'
export const SET_LOGLIST_IMEIS = 'SET_LOGLIST_IMEIS'
export const SET_LOGLIST_LOGS = 'SET_LOGLIST_LOGS'
export const SET_LOGLIST_LOADING = 'SET_LOGLIST_LOADING'
// backend
export const SET_BACKEND_APPS = 'SET_BACKEND_APPS'
